CREATE DATABASE IF NOT EXISTS `camino_santiago`;
USE `camino_santiago`;




CREATE TABLE IF NOT EXISTS `df_routes` (
	`ID` BIGINT NOT NULL AUTO_INCREMENT UNIQUE,
	`route_id` BIGINT NOT NULL,
	`Year` INTEGER NOT NULL,
	`Month` TINYINT NOT NULL,
	`French Way` INTEGER NOT NULL,
	`Via de la Plata` INTEGER NOT NULL,
	`Primitive Way` INTEGER NOT NULL,
	`Portuguese Way` INTEGER NOT NULL,
	`Northern Way` INTEGER NOT NULL,
	`English Way` INTEGER NOT NULL,
	`Other Ways` INTEGER NOT NULL,
	`Muxia-Finisterre` INTEGER NOT NULL,
	PRIMARY KEY(`ID`)
);


CREATE TABLE IF NOT EXISTS `df_groups` (
	`ID` BIGINT NOT NULL AUTO_INCREMENT UNIQUE,
	`Year` INTEGER NOT NULL,
	`Month` TINYINT NOT NULL,
	`Students` INTEGER NOT NULL,
	`Workers` INTEGER NOT NULL,
	`Freelancers` INTEGER NOT NULL,
	`Employees` INTEGER NOT NULL,
	`Teachers` INTEGER NOT NULL,
	`Technicians` INTEGER NOT NULL,
	`Public_Servants` INTEGER NOT NULL,
	`Unemployed` INTEGER NOT NULL,
	`Housewives` INTEGER NOT NULL,
	`other_works` INTEGER NOT NULL,
	`Retirees` INTEGER NOT NULL,
	PRIMARY KEY(`ID`)
);


CREATE TABLE IF NOT EXISTS `df_countries` (
	`ID` BIGINT NOT NULL AUTO_INCREMENT UNIQUE,
	`Year` INTEGER NOT NULL,
	`Month` TINYINT NOT NULL,
	`Spain` INTEGER NOT NULL,
	`Germany` INTEGER NOT NULL,
	`Italy` INTEGER NOT NULL,
	`United States` INTEGER NOT NULL,
	`Portugal` INTEGER NOT NULL,
	`France` INTEGER NOT NULL,
	`other_countries` INTEGER NOT NULL,
	PRIMARY KEY(`ID`)
);


CREATE TABLE IF NOT EXISTS `df_continents` (
	`ID` BIGINT NOT NULL AUTO_INCREMENT UNIQUE,
	`Year` INTEGER NOT NULL,
	`Month` TINYINT NOT NULL,
	`Europa` INTEGER NOT NULL,
	`Oceania` INTEGER NOT NULL,
	`Asia` INTEGER NOT NULL,
	`Africa` INTEGER NOT NULL,
    `Total` INTEGER NOT NULL,
	`America` INTEGER NOT NULL,
	PRIMARY KEY(`ID`)
);


CREATE TABLE IF NOT EXISTS `df_gender` (
	`ID` BIGINT NOT NULL AUTO_INCREMENT UNIQUE,
	`Year` INTEGER NOT NULL,
	`Month` TINYINT NOT NULL,
	`Men` INTEGER NOT NULL,
	`Women` INTEGER NOT NULL,
	`Total` INTEGER NOT NULL,
	PRIMARY KEY(`ID`)
);


CREATE TABLE IF NOT EXISTS `df_motives` (
	`ID` BIGINT NOT NULL AUTO_INCREMENT UNIQUE,
	`Year` INTEGER NOT NULL,
	`Month` TINYINT NOT NULL,
	`Religious` INTEGER NOT NULL,
	`Non-Religious` INTEGER NOT NULL,
	PRIMARY KEY(`ID`)
);


CREATE TABLE IF NOT EXISTS `df_trans` (
	`ID` BIGINT NOT NULL AUTO_INCREMENT UNIQUE,
	`route_id` BIGINT NOT NULL,
	`Year` INTEGER NOT NULL,
	`Month` TINYINT NOT NULL,
	`Foot` INTEGER NOT NULL,
	`Bicycle` INTEGER NOT NULL,
	`Other trans` INTEGER NOT NULL,
	PRIMARY KEY(`ID`)
);


CREATE TABLE IF NOT EXISTS `df_ages` (
	`ID` BIGINT NOT NULL AUTO_INCREMENT UNIQUE,
	`Year` INTEGER NOT NULL,
	`Month` TINYINT NOT NULL,
	`<40` INTEGER NOT NULL,
	`>=40` INTEGER NOT NULL,
	PRIMARY KEY(`ID`)
);


CREATE TABLE IF NOT EXISTS `df_pilgrins` (
	`ID` BIGINT NOT NULL AUTO_INCREMENT UNIQUE,
	`Men` INTEGER NOT NULL,
	`Women` INTEGER NOT NULL,
	`=>40` INTEGER NOT NULL,
	`<40` INTEGER NOT NULL,
	PRIMARY KEY(`ID`)
);


-- QUERY 1: df_gender - Evolution % Women
SELECT Year, 
       ROUND(SUM(Women) / SUM(Total) * 100, 2) AS pct_women,
       SUM(Men) AS homens,
       SUM(Women) AS mulheres
FROM df_gender 
GROUP BY Year 
ORDER BY Year DESC 
LIMIT 10;

-- QUERY 2: df_countries - Top countries 2022+
SELECT Year, Spain, Germany, `United States`, Portugal, France
FROM df_countries 
WHERE Year >= 2020
ORDER BY Year DESC, Spain DESC 
LIMIT 12;

-- QUERY 3: df_continents - Continents per recent year
SELECT Year, 
       SUM(Europa) AS Europa,
       SUM(America) AS America,
       SUM(Oceania + Asia + Africa) AS resto_mundo
FROM df_continents 
GROUP BY Year 
ORDER BY Year DESC 
LIMIT 10;

-- QUERY 4: df_ages - Mean of age per year
SELECT Year, 
       SUM(`<40`) AS jovens,
       SUM(`=>40`) AS adultos_40mais,
       ROUND(SUM(`<40`)/SUM(Total)*100,2) AS pct_jovens
FROM df_ages 
GROUP BY Year 
ORDER BY Year DESC 
LIMIT 10;


-- QUERY 5: CROSS-ANALYSIS GENDER x COUNTRIES 2022
SELECT Year, 
       Spain, Germany, `United States`,
       (SELECT SUM(Women) FROM df_gender WHERE Year = c.Year) AS total_women
FROM df_countries c 
WHERE Year = 2022;



ALTER TABLE `df_routes`
ADD FOREIGN KEY(`ID`) REFERENCES `df_trans`(`ID`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `df_motives`
ADD FOREIGN KEY(`ID`) REFERENCES `df_pilgrins`(`ID`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `df_pilgrins`
ADD FOREIGN KEY(`ID`) REFERENCES `df_ages`(`ID`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `df_trans`
ADD FOREIGN KEY(`ID`) REFERENCES `df_pilgrins`(`ID`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `df_countries`
ADD FOREIGN KEY(`ID`) REFERENCES `df_continents`(`ID`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `df_groups`
ADD FOREIGN KEY(`ID`) REFERENCES `df_pilgrins`(`ID`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `df_pilgrins`
ADD FOREIGN KEY(`ID`) REFERENCES `df_gender`(`ID`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `df_pilgrins`
ADD FOREIGN KEY(`ID`) REFERENCES `df_countries`(`ID`)
ON UPDATE NO ACTION ON DELETE NO ACTION;